name: Blocksmurfer Unittests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install cython
          pip install coveralls
          pip install scrypt
          python setup.py install
          cp config.example.py config.py
          git clone https://github.com/1200wd/bitcoinlib.git 1200wd/bitcoinlib
          ln -s 1200wd/bitcoinlib/bitcoinlib bitcoinlib
      - name: Test with covarage
        run: coverage run --source=blocksmurfer -m unittest -v
#      - name: Run Coveralls
#        env:
#          GITHUB_TOKEN: $ secrets.GITHUB_TOKEN
#        run: coveralls --service=github
